### ISSUE TITLE
Poor Sampling Behaviour?

### ISSUE THREAD

**Issue by steinitznavican** [jtobin/hasty-hamiltonian#3]
I am probably doing something wrong but I tried this

```
myStdNormal :: RealFloat a => [a] -> a
myStdNormal [x] = recip (sqrt (2 * pi)) * exp (-(x * x) / 2)
myStdNormal _   = error "myStdNormal"

gStd :: [Double] -> [Double]
gStd = grad myStdNormal

bStd :: Target [Double]
bStd = Target myStdNormal (Just gStd)

results <- withSystemRandom . asGenIO $ chain 10000 0.05 8 [0.0] bStd
```

But I get

```
sum $ concatMap chainPosition results

-88654.39040183097
```

**Comment by steinitznavican** [comment]
I just tried the Rosenbrock example in the repo and AFAICT it gets nowhere near the minimum (1,1) - see https://en.wikipedia.org/wiki/Rosenbrock_function

```
main :: IO ()
main = do
  xs <- withSystemRandom . asGenIO $ chain 10000 0.05 20 [0, 0] rosenbrock
  putStrLn $ show $ sum $ map (!!0) $ drop 5000 $ map chainPosition xs
  putStrLn $ show $ sum $ map (!!1) $ drop 5000 $ map chainPosition xs
```

```
3307.1528055591994
3405.753360195919
```

**Comment by jtobin** [comment]
There are a few issues or potential issues here:

* You should be averaging -- not summing -- the chain positions, in order to get a Monte Carlo estimate of the expectation.  At present you're adding together a bunch of positions, which does not produce a particularly meaningful statistic.

* MCMC is useful for estimating expectations, not optima.  The chain itself should spend time in a given region of parameter space in proportion to its density -- if I run the Rosenbrock example and plot the chain positions, I see that the chain indeed spends plenty of time wandering around near the maximum (note *maximum*: this is not the Rosenbrock function, but the Rosenbrock *density*).

* Hamiltonian Monte Carlo is annoying and hard to use.  Setting the step size and number of leapfrog iteration parameters correctly is difficult, and "bad" values will lead to bad samples.

(There could also certainly be a bug in my implementation, but I am fairly confident that I at least had it right at some point, so I'd need more evidence that something is awry before I delve into it too deeply.)

**Comment by steinitznavican** [comment]
Oh so I should have done this?

```
myStdNormal :: RealFloat a => [a] -> a
myStdNormal [x] = recip (sqrt (2 * pi)) * exp (-((x - 0.1) * (x - 0.1)) / 2)
myStdNormal _   = error "myStdNormal"

gStd :: [Double] -> [Double]
gStd = grad myStdNormal

bStd :: Target [Double]
bStd = Target myStdNormal (Just gStd)
```

```
main :: IO ()
main = do
  let l = 10000
  results <- withSystemRandom . asGenIO $ chain l 0.005 8 [0.1] bStd
  let ps :: [[Double]]
      ps = map chainPosition results
      vs :: [Double]
      vs = map chainScore results
      es = zipWith (*) (concat ps) vs
  putStrLn $ show $ (*(recip (fromIntegral l))) $ sum es
```

That doesn't seem to give quite the right answers though. Running `main` a few times gives

```
-7.12510699922022e-2
5.56138665233156e-2
4.826710569086873e-2
-5.573019117343454e-3
```

I would have hoped it would be nearer to 0.1.

As you say HMC is hard to tune hence NUTS.

Actually all I want is to be able to sample a distribution and I happen to have the gradient. Any suggestions would be warmly received.

**Comment by jtobin** [comment]
Right, I took a look at your example:

* Your target needs to be a log-density.  Instead of 

      recip (sqrt (2 * pi)) * exp (-((x - 0.1) * (x - 0.1)) / 2)

  Use:

      -((x - 0.1) * (x - 0.1)) / 2

  (you can ditch the multiplicative constant term here)

* You don't want to weight each term by the score (which is not a probability, but the logarithm of something proportional to a probability).  Instead just use the empirical measure, i.e. a direct average of the points you've observed:

      ps = map chainPosition results
      ex = sum ps / fromIntegral (length ps)

* Your step size might be too small, and your number of leapfrog iterations too low.  Again, as you point out, this is just a matter of HMC tuning annoyance.  But using `0.05` and `20`, I got the following on a few runs:

```
*Main> foo
0.10512744981232493
*Main> foo
0.10637706671733922
*Main> foo
7.84747400680845e-2
*Main> foo
0.11026280202297518
```

> Actually all I want is to be able to sample a distribution and I happen to have the gradient. 

HMC will certainly do this for you, if you can get the tuning parameters right.  I do actually have an old (and very carefully-implemented) [NUTS implementation](https://github.com/jtobin/hnuts) coded up, but it is possibly in need of some TLC.  You can give it a shot, though.  Some examples are [here](https://github.com/jtobin/hnuts/blob/master/src/Numeric/MCMC/NUTS/Examples.hs).

Alternatively you can try the [affine-invariant ensemble sampler](https://github.com/jtobin/flat-mcmc), which is pretty reliable and very easy to use, or the eminently-reliable [slice sampler](https://github.com/jtobin/speedy-slice).  Neither requires a gradient, but are very handy.
